import type { Metadata } from "next";
import { Geist} from "next/font/google";
import "./globals.css";

const geist = Geist({
	subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Orbit",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
		<html lang="en" className={geist.className}>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
  );
}
